### ISSUE TITLE
How to link the located particles

### ISSUE THREAD

**Issue by XinyueZhang831** [softmatterlab/DeepTrack-2.0#126]
Hi,

I am using the multiple particle tracking example notebook, and it works fine. But I realized that it is only the localization, do you have the linking part of this notebook?

**Comment by BenjaminMidtvedt** [comment]
Hi! We do have tools for linking as well as detecting. examples/MAGIK contains an example of using our graph-based neural network for tracing. @JesusPinedaC should be able to help more with this! 

If the tracing is not too complicated, you can also use a non-deep-learning approach. Let me know if that is of interest.

**Comment by JesusPinedaC** [comment]
Hi @XinyueZhang831 

[In this link](https://github.com/softmatterlab/DeepTrack-2.0/tree/develop/examples/MAGIK), you will find an example of using MAGIK, our graph-based neural network, for detection linking.

MAGIK requires annotated data to be trained—however, a minimal amount of training data has proven to be sufficient to achieve accurate results.

Applying a pre-trained model directly to your data is also possible if a training dataset isn't available. This model has proven to be quite generalizable, capable of adjusting to various movement dynamics. Follow the instructions in the example to download the model. 

If you want to know more about MAGIK, [here is the paper](https://arxiv.org/abs/2202.06355).

**Comment by XinyueZhang831** [comment]
> 
Hi Benjamin and Jesus,

Thank you for providing the example of MAGIK! The work looks fantastic! May I ask if I have to have the parenthood to use the GraphGenerator?

**Comment by JesusPinedaC** [comment]
Hello @XinyueZhang831 !

No, parenthood is totally optional. It is helpful in cases where you want to encode specific interactions between particles in the graph, for example, cell divisions or merging events.

However, omit this argument if you are not interested in including this information in the graph representation. DeepTrack will handle it!

**Comment by XinyueZhang831** [comment]
> Hello @XinyueZhang831 !
> 
> No, parenthood is totally optional. It is helpful in cases where you want to encode specific interactions between particles in the graph, for example, cell divisions or merging events.
> 
> However, omit this argument if you are not interested in including this information in the graph representation. DeepTrack will handle it!

Hi Jesus,

I was trying to run the code on notebook, but I did not find the pre-trained model. Does this repo includes the pre-trained model?

Also, if I disable the _LOAD_MODEL, an error occurs as following:

Creating graph edges...
100%|██████████| 1/1 [00:52<00:00, 52.76s/it]
Generating 512 / 511 samples before starting training
Epoch 1/10
/usr/local/lib/python3.7/dist-packages/deeptrack/image.py:317: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(self.to_numpy()._value)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-12-e124459faecc>](https://localhost:8080/#) in <module>()
     16 
     17     with generator:
---> 18         model.fit(generator, epochs=10)

2 frames
[/usr/local/lib/python3.7/dist-packages/deeptrack/models/utils.py](https://localhost:8080/#) in fit(self, x, batch_size, generator_kwargs, *args, **kwargs)
    245             return None
    246 
--> 247         return self.model.fit(x, *args, **kwargs)
    248 
    249     def export(

[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'model/graph_block_0/GatherV2' defined at (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
      handle._run()
    File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 661, in <lambda>
      self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
      self._handle_recv()
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
      self._run_callback(callback, msg)
    File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
      callback(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
      return self.dispatch_shell(stream, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
      handler(stream, idents, msg)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
      user_expressions, allow_stdin)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
      interactivity=interactivity, compiler=compiler, result=result)
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
      if self.run_code(code, result):
    File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-11-6e5d703ebab1>", line 17, in <module>
      model.fit(generator, epochs=10)
    File "/usr/local/lib/python3.7/dist-packages/deeptrack/models/utils.py", line 247, in fit
      return self.model.fit(x, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 452, in call
      inputs, training=training, mask=mask)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/deeptrack/models/gnns/layers.py", line 84, in call
      message_inputs = tf.gather(nodes, edges, batch_dims=1)
Node: 'model/graph_block_0/GatherV2'
indices[6,3793,1] = 1020 is not in [0, 1019)
	 [[{{node model/graph_block_0/GatherV2}}]] [Op:__inference_train_function_12591]

It would be great if you would have any suggestions.
Thank you!

**Comment by JesusPinedaC** [comment]
Hi @XinyueZhang831!

Thanks for reporting this issue!

Currently, we are working on it and hope to have it fixed by tomorrow.

**Comment by JesusPinedaC** [comment]
Hi @XinyueZhang831!

We have released deeptrack v1.3.1. This new version fixes the bug. Please try it out and let us know if you have any other questions.

The pre-trained model is provided together with the BFC2Cells dataset, which is downloaded in Section 2.1 of the example. Don't forget to run this cell before trying to load the model weights.

**Comment by JesusPinedaC** [comment]
Please reopen if the issue persists
